### PR TITLE
Added even more tests

### PR DESCRIPTION
**Pull request by SrTobi**
Abgabe von Gruppe 2 für Aufgabe 1.3

### CODE REVIEW

**Comment by parttimenerd** [comment]
I removed the non ASCII test as the language specification only says, that the input is ASCII encoded. It doesn't specify what to do with non ASCII characters.

**Comment by SrTobi** [comment]
It is true that `\xff` is not an ascii char but `\x00` is.

**Comment by parttimenerd** [comment]
You're correct. Please add a new testcase that tests the acceptance of `\x00`.

**Comment by SrTobi** [comment]
ähh... that was our `\x00` acceptance test... just revert the commit where you removed it and remove the `\xff`

**Comment by sgraf812** [comment]
Happened in PR #4.

**Pull request merged**
