### PR TITLE
Add tests of Group 1

### PR DESCRIPTION
**Pull request by FlorianLoch**

### CODE REVIEW

**Comment by sgraf812** [comment]
I'm sorry, merging this was a little premature...

1. decision_between_localVarDecl_and_statement.mj: Fails, but rightly so: `public int b = 0;` is invalid
2. empty_statements.mj: `int field1 = 0;` also invalid (no public and field init)
3. new_array_expression.mj: Same
4. parsing_recursion.mj: Invalid syntax: `while` is not allowed in the body of a class.
5. simple_class.mj: Invalid syntax: `while` in class body

@parttimenerd is working on fixing them, though.

**Comment by FlorianLoch** [comment]
Sorry for that, we can fix them too..

--
Florian Loch
florian.loch@gmail.com <mailto:florian.loch@gmail.com>
Klosterweg 28 C314
76131 Karlsruhe

**Comment by parttimenerd** [comment]
I fixed all your test cases, but removed the `parsing_recursion.mj` test case as the recursion is inherently in the grammar specification. Testing against it doesn't make any sense (to me).

**Comment by sgraf812** [comment]
In particular, blowing up the stack at some point is inevitable, since the respective productions are neither left nor right recursive, thus can't be implemented without blowing up the stack (as opposed to something like parameter lists of arbitrary length).

**Comment by FlorianLoch** [comment]
We know - just wanted to add a non-standard testcase to create some
awareness and maybe kickoff a more generell discussion about how nested
code can actually be and whether Java and other language actually have a
nesting-limit ;)

But you are right, it might not be to handy for pragmatic testing.

**Comment by FlorianLoch** [comment]
Thank you for fixing, but we could have done that on ourselves too ;)

Regarding the recursion file:
We just wanted to add a non-standard testcase to create some awareness and
maybe kickoff a more generell discussion about how nested code can actually
be and whether Java and other language actually have a nesting-limit ;)

But you are right, it might not be to handy for pragmatic testing.

**Pull request merged**
